### ISSUE TITLE
某国产企业办公软件自带的JDK在添加热部署代理后无法启动服务

### ISSUE THREAD

**Issue by jinglekang** [Liubsyy/HotSecondsIDEA#10]
> 如下图所示：
![image](https://github.com/thanple/HotSecondsIDEA/assets/17934343/6ee788a1-2ffa-4a64-8ca5-2557127d1d54)

**Comment by Liubsyy** [comment]
这是输入java -version就报错了吗

**Comment by Liubsyy** [comment]
你装普通的jdk181以下的版本试一下

**Comment by jinglekang** [comment]
> 你装普通的jdk181以下的版本试一下

安装原版的oraclejdk后，启动会报这个错误，我再研究研究
![image](https://github.com/thanple/HotSecondsIDEA/assets/17934343/284cf6fd-302b-474e-ae0f-08b715109240)

**Comment by jinglekang** [comment]
> > 你装普通的jdk181以下的版本试一下
> 
> 安装原版的oraclejdk后，启动会报这个错误，我再研究研究 ![image](https://user-images.githubusercontent.com/17934343/260181300-284cf6fd-302b-474e-ae0f-08b715109240.png)

我使用了-UserG1GC后没有这个提示了，但是还是有其他报错
`Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsatisfiedLinkError: C:\Seeyon\HotSecondsServer\lib\boot.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.liubs.HotSecondsBoot.<clinit>(Unknown Source)
        at com.liubs.HotSecondsEntrance.start0(Native Method)
        at com.liubs.HotSecondsEntrance.premain(HotSecondsEntrance.java:34)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsatisfiedLinkError: C:\Seeyon\HotSecondsServer\lib\boot.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.liubs.HotSecondsBoot.<clinit>(Unknown Source)
        at com.liubs.HotSecondsEntrance.start0(Native Method)
        at com.liubs.HotSecondsEntrance.premain(HotSecondsEntrance.java:34)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Using CATALINA_BASE:   "C:\Seeyon\A8\ApacheJetspeed\bin\\.."
Using CATALINA_HOME:   "C:\Seeyon\A8\ApacheJetspeed\bin\\.."
Using CATALINA_TMPDIR: "C:\Seeyon\A8\ApacheJetspeed\bin\\..\temp"
Using JRE_HOME:        "C:\Seeyon\A8\ApacheJetspeed\bin\\..\..\jdk"
Using CLASSPATH:       "C:\Seeyon\A8\ApacheJetspeed\bin\\..\bin\bootstrap.jar;C:\Seeyon\A8\ApacheJetspeed\bin\\..\bin\tomcat-juli.jar"
Using CATALINA_OPTS:   ""
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.UnsatisfiedLinkError: C:\Seeyon\HotSecondsServer\lib\boot.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.liubs.HotSecondsBoot.<clinit>(Unknown Source)
        at com.liubs.HotSecondsEntrance.start0(Native Method)
        at com.liubs.HotSecondsEntrance.premain(HotSecondsEntrance.java:34)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed

C:\Seeyon\A8\ApacheJetspeed\bin>`

**Comment by Liubsyy** [comment]
这个热部署需要支持新增字段和方法，只能用Serial GC，不能用其他GC，你把GC相关参数都去掉就行了

**Comment by jinglekang** [comment]
> 这个热部署需要支持新增字段和方法，只能用Serial GC，不能用其他GC，你把GC相关参数都去掉就行了

移除默认的-XX:+UseG1GC，添加上-XX:+UseSerialGC，启动时还是报楼上的异常信息

**Comment by jinglekang** [comment]
> 看来你的电脑可能缺少链接库，我把所有的依赖都打包到boot.dll了，发布了HotSecondsServer-beat5，你下载这个版本试一下应该没问题了

感谢，在打包依赖后，启动服务时可以正常输出HotDeployService热部署服务启动成功，但是没有继续加载产品的环境，这种情况遇到过么

**Comment by Liubsyy** [comment]
没有继续加载产品的环境，是指程序没有继续往下启动初始化吗？没有遇到过，你可以看看报错信息，或者用jstack看看主线程是不是阻塞住了

**Comment by jinglekang** [comment]
> 没有继续加载产品的环境，是指程序没有继续往下启动初始化吗？没有遇到过，你可以看看报错信息，或者用jstack看看主线程是不是阻塞住了

我暂时搞不定了，启动服务只提示下面这些，也没有其他日志

```
Listening for transport dt_socket at address: 5005
HOTSECONDS: 08:34:20.921 INFO Add tools.jar to classpath...
HOTSECONDS: 08:34:21.071 INFO findAllDependencyClasses[]
HOTSECONDS: 08:34:21.071 INFO findAllDependencyClasses[C:\Seeyon\A8\ApacheJetspeed\bin\bootstrap.jar, C:\Seeyon\A8\ApacheJetspeed\bin\commons-daemon.jar, C:\Seeyon\A8\ApacheJetspeed\bin\jdom.jar, C:\Seeyon\A8\ApacheJetspeed\bin\startup_tomcat.jar, C:\Seeyon\A8\ApacheJetspeed\bin\tomcat-juli.jar]
HOTSECONDS: 08:34:21.071 INFO Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSECONDS: 08:34:21.650 INFO Discovered plugins: [MyBatis, Hotswapper, JdkPlugin, AnonymousClassPatch, ClassInitPlugin, WatchResources, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow]
========== JMMysqlProxyDriver loaded successfully ==========
HOTSECONDS: 08:34:24.884 INFO HotDeployService热部署服务启动成功
```

**Comment by Liubsyy** [comment]
服务器没启动成功，也没报错，可以先检查一下把GC相关的jvm参数都删掉，包括但不限于 -XX:+UseParNewGC, -XX:+UseConcMarkSweepGC，-XX:ParallelGCThreads ,-XX:+UseCMSCompactAtFullCollection ,-XX:CMSInitiatingOccupancyFraction 等等，如果不确定可以先只加最基本的jvm参数看看能不能起来。
