### ISSUE TITLE
热部署失败

### ISSUE THREAD

**Issue by lijunjie1991** [Liubsyy/HotSecondsIDEA#16]
我配置的连接ip地址是服务器的外网ip地址，但是这个报错里面是服务器的内网ip地址

<img width="640" alt="image" src="https://github.com/thanple/HotSecondsIDEA/assets/106374688/7715c6db-6da4-45e3-b8b5-f79d722dc0de">

报错中10.10.0.82是我的服务器的内网ip地址

能不能提供一下HotDeployClient这个类的源码看一看。。

```
[14:22:51] Failed to initialize IHotDeployService:java.rmi.ConnectException: Connection refused to host: 10.10.0.82; nested exception is: 
	java.net.ConnectException: Operation timed out
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:626)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:217)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:204)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:133)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:215)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)
	at jdk.proxy16/jdk.proxy16.$Proxy292.hello(Unknown Source)
	at com.liubs.ff.hotdeploy.HotDeployClient.lambda$initHotDeployConnectAsync$2(HotDeployClient.java:94)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at com.intellij.execution.rmi.RemoteServer$1.createSocket(RemoteServer.java:156)
	at java.rmi/sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:620)
	... 9 more
```

**Comment by Liubsyy** [comment]
一般来说直接填内网ip就行，如果你一定要通过外网访问，可以在服务端加上-Djava.rmi.server.hostname=外网ip，这样客户端就直接和外网ip通信了，另外要确保外网端口能映射到内网的端口

**Comment by Liubsyy** [comment]
另外服务器包也需要升级到HotSecondsServer-future2版本

**Comment by c0febean** [comment]
不知道题主按照作者的方式解决没有, 这个报错我也遇到过, 我是在wsl里运行的服务端, 连接出现该异常后, 修改了hostname 相关的映射就好了, 参照这个 [https://blog.csdn.net/chenchaofuck1/article/details/51558995](https://blog.csdn.net/chenchaofuck1/article/details/51558995)

**Comment by nanxing7** [comment]
> 不知道题主按照作者的方式解决没有, 这个报错我也遇到过, 我是在wsl里运行的服务端, 连接出现该异常后, 修改了hostname 相关的映射就好了, 参照这个 https://blog.csdn.net/chenchaofuck1/article/details/51558995

感谢 , 通过 hotsname -i 查看到 ip 是 127.0.0.1 通过 hostname 查看到 hostname 是 debian , 我就去 /etc/hosts 目录下把 127.0.0.1 deian 改为 外网 IP debian 就可以连上了
