### ISSUE TITLE
Connection refused to host: 127.0.0.1

### ISSUE THREAD

**Issue by wgx1995** [Liubsyy/HotSecondsIDEA#40]
[19:02:12] [127.0.0.1:8089] Initialized hot-seconds.xml:HotDeployConfig{ author='liubsyy', secret='123', remoteIp='127.0.0.1', remotePort=8089, connections=[Connection{secret='123', ip='127.0.0.1', port=8089}], timeout=3000, autoHotDeploy=false, mappings=[]}
[19:02:12] [127.0.0.1:8089] Failed to initialize IHotDeployService:java.rmi.ConnectIOException: non-JRMP server at remote endpoint
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:244)
	at java.rmi/sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:196)
	at java.rmi/sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
	at com.liubs.ff.hotdeploy.HotDeployClient.lambda$initHotDeployConnectAsync$2(HotDeployClient.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Liubsyy** [comment]
看看端口起来没，是不是和服务器启动的同一个端口，可以换个端口试试

**Comment by wgx1995** [comment]
服务的端口起来了    换了端口也是同样的问题  在插件上填的端口  不应该填服务的端口吗  还是填什么呢？
