### ISSUE TITLE
jdk8_191版本，Linux-x64，启动报stackoverflow

### ISSUE THREAD

**Issue by Foolisher** [Liubsyy/HotSecondsIDEA#63]
HOTSECONDS: 19:41:47.967 INFO HotSeconds热部署服务启动成功

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.StackOverflowError
	at io.opentelemetry.javaagent.bootstrap.InjectedClassHelper.loadHelperClass(InjectedClassHelper.java:55)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.opentelemetry.javaagent.bootstrap.InjectedClassHelper.loadHelperClass(InjectedClassHelper.java:55)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.opentelemetry.javaagent.bootstrap.InjectedClassHelper.loadHelperClass(InjectedClassHelper.java:55)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by Liubsyy** [comment]
opentelemetry这个agent和热部署agent冲突了，只能下掉opentelemetry了
