### ISSUE TITLE
上传jar包失败

### ISSUE THREAD

**Issue by mr-nealon** [Liubsyy/HotSecondsIDEA#68]
linux与本地连接成功，只关联了jar包，更新服务器jar包时，异常

![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/153061817/96aa139f-acb3-45b4-a34e-c5c774452d38)

[14:10:20] [172.18.10.65:12024] Initialized hot-seconds.xml:HotDeployConfig{ author='liubsyy', secret='liubsyy$aaaaaaaabbbbbbbbbccccccccc', remoteIp='172.18.10.65', remotePort=12024, timeout=3000, autoHotDeploy=true, mappings=[Mapping{fileType=[.jar], path='E:/0508pig/platform/platform/platform-boot/target', remotePath='/home/aircas/deploy/backend'}], connections=[Connection{name='', secret='aaaaaaaabbbbbbbbbccccccccc', ip='172.18.10.65', port=12024}], proxy=false, proxyHost='', proxyPort=0}
[14:10:20] [172.18.10.65:12024] Start listening for file changes in directory [[E:/0508pig/platform/platform/platform-boot/target]]
[14:10:20] [172.18.10.65:12024] Initialized remote hot deployment client completed, took 14 ms
[14:10:20] requestRemoteLoader[]
[14:10:27] Hot deploy selected file：[E:/platform/platform-boot/target/platform-boot.jar]
[14:10:27] [172.18.10.65:12024] *** BatchReloadingResourceFile START,items=1 *** 
[14:10:27] [172.18.10.65:12024] UploadResourceFile,remotePath=/home/aircas/deploy/backend/platform-boot.jar,size=135905726
[14:10:31] [172.18.10.65:12024] UploadResourceFile err/home/aircas/deploy/backend/platform-boot.jar:java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy17/jdk.proxy17.$Proxy325.uploadResourceFile(Unknown Source)
	at com.liubs.ff.hotdeploy.BatchModifiedClient$1.run(BatchModifiedClient.java:166)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.liubs.ff.aop.RemoteConnectionHandler.invoke(RemoteConnectionHandler.java:44)
	... 5 more
Caused by: java.rmi.MarshalException: error marshalling arguments; nested exception is: 
	java.net.SocketException: 你的主机中的软件中止了一个已建立的连接。
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:215)
	at java.rmi/java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)
	at jdk.proxy17/jdk.proxy17.$Proxy325.uploadResourceFile(Unknown Source)
	... 10 more
Caused by: java.net.SocketException: 你的主机中的软件中止了一个已建立的连接。
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:425)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:445)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:831)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1035)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1886)
	at java.base/java.io.ObjectOutputStream$BlockDataOutputStream.writeByte(ObjectOutputStream.java:1924)
	at java.base/java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1601)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at java.rmi/sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:294)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:156)
	... 13 more

[14:10:31] [172.18.10.65:12024] *** BatchReloadingResourceFile END,passes 3519 ms ***

**Comment by Liubsyy** [comment]
你直接热部署java代码就行了，配置jar干什么？

**Comment by Liubsyy** [comment]
热部署jar不需要配置，是在jar内打开的class右键->热部署jar

**Comment by mr-nealon** [comment]
热部署直接使用HotSeconds更新java文件就可以是吗

**Comment by mr-nealon** [comment]
热更新java文件有报错

![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/153061817/8e5e9330-e14f-4701-8143-81125d24bc02)

**Comment by Liubsyy** [comment]
是的，直接热更新java就行了，还得打jar包也太麻烦了。
有关Hibernate的报错都可以忽略，你看看有没有生效

**Comment by mr-nealon** [comment]
上传成功后本地没有报错，服务器端报错了，没生效

**Comment by mr-nealon** [comment]
![image](https://github.com/Liubsyy/HotSecondsIDEA/assets/153061817/eb3c6fc4-3855-4775-9a04-709ba69968fd)

**Comment by Liubsyy** [comment]
有没有自定义ClassLoader ?  看着 com.train.platform.admin.api.entity.SysProgram 不是SpringBoot加载的
