### ISSUE TITLE
java.lang.InternalError: JVM_GetClassContext must only be called from SecurityManager.getClassContext

### ISSUE THREAD

**Issue by divertus** [Liubsyy/HotSecondsIDEA#69]
jdk 版本x86 1.8.0_181
dcevm 版本1.8.0_181
进程启动时报错

java.lang.InternalError: JVM_GetClassContext must only be called from SecurityManager.getClassContext
	at java.lang.SecurityManager.getClassContext(Native Method)
	at javassist.util.proxy.SecurityActions.getCallerClass(SecurityActions.java:54)
	at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:174)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	at javassist.ClassPool.toClass(ClassPool.java:1240)
	at javassist..toClass(CtClass.java:1392)

javassist-3.29.2-GA.jar

**Comment by Liubsyy** [comment]
具体是怎么增强导致的呢？能否给一个能复现的最小项目例子，越简单越好，但是要完整的例子

**Comment by divertus** [comment]
> 具体是怎么增强导致的呢？能否给一个能复现的最小项目例子，越简单越好，但是要完整的例子

应该和这个没关系，jvm crash了
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/NoClassDefFoundError'> (0x000000008812fe08) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux/hotspot/src/share/vm/prims/jvm.cpp, line 1395]
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/InternalError': JVM_GetClassContext must only be called from SecurityManager.getClassContext> (0x0000000088133518) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/InternalError': JVM_GetClassContext must only be called from SecurityManager.getClassContext> (0x0000000088140160) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/InternalError': JVM_GetClassContext must only be called from SecurityManager.getClassContext> (0x0000000088145de8) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/InternalError': JVM_GetClassContext must only be called from SecurityManager.getClassContext> (0x000000008814b268) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux
Event: 12.490 Thread 0x00007ff010006800 Exception <a 'java/lang/InternalError': JVM_GetClassContext must only be called from SecurityManager.getClassContext> (0x000000008814fec0) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux
Event: 13.129 Thread 0x00007ff091058000 Implicit null exception at 0x00007ff0745bc48b to 0x00007ff0745bd101
Event: 13.129 Thread 0x00007ff091058000 Exception <a 'java/lang/NullPointerException'> (0x0000000088bf0b40) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 605]
Event: 13.131 Thread 0x00007ff091058000 Implicit null exception at 0x00007ff0745bc48b to 0x00007ff0745bd101
Event: 13.131 Thread 0x00007ff091058000 Exception <a 'java/lang/NullPointerException'> (0x0000000088c131e0) thrown at [/var/lib/jenkins/workspace/DCEVM-8u161/jdk/JDK1.8.0_181-x64/k/product/oops/nocompressed/slave/dcevm-linux/hotspot/src/share/vm/runtime/sharedRuntime.cpp, line 605]
