### ISSUE TITLE
使用代理模式IDEA侧启动插件失败

### ISSUE THREAD

**Issue by chensanpi** [Liubsyy/HotSecondsIDEA#75]
操作系统：Apple M3
JDK：17
HotSecondsClient版本：2.1.1
![image](https://github.com/user-attachments/assets/274842ec-dc8c-43ff-a7fe-87afd123cede)

HotSecondsServer：7.1
![image](https://github.com/user-attachments/assets/7f4673f6-b51a-4597-b226-150d647f8e22)

HotSecondsProxy：1.0

HotSecondsProxy已经启动！外网地址：120.79.133.139
HotSecondsServer内网地址：172.29.79.250

hot-seconds.xml 核心配置：
![image](https://github.com/user-attachments/assets/b41d9429-9f67-4ea5-8ea6-5848495bde9e)

IDEA点击【Start HotSeconds】报错
[21:16:14] [172.29.79.250:2024] Initialized hot-seconds.xml:HotDeployConfig{ author='liubsyy', secret='hunjuice-hotswap-secret', remoteIp='172.29.79.250', remotePort=2024, timeout=30000, autoHotDeploy=false, mappings=[], connections=[Connection{name='', secret='hunjuice-hotswap-secret', ip='172.29.79.250', port=2024}], proxy=true, proxyHost='120.79.133.139', proxyPort=12023}
[21:16:14] [172.29.79.250:2024] Failed to initialize IHotDeployService:java.lang.RuntimeException: 无法连接目标服务器[172.29.79.250:2024]
	at com.liubs.ff.proxyserver.TargetServerHandler.invoke(TargetServerHandler.java:48)
	at jdk.proxy17/jdk.proxy17.$Proxy266.hello(Unknown Source)
	at com.liubs.ff.hotdeploy.InitClientFutureCallable.call(InitClientFutureCallable.java:63)
	at com.liubs.ff.hotdeploy.InitClientFutureCallable.call(InitClientFutureCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Liubsyy** [comment]
加群沟通

**Comment by chensanpi** [comment]
已加
